// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ms_patients_consul_core.Infrastructure.Persistence;

#nullable disable

namespace ms_patients_consul_core.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(PatientsConsultationDbContext))]
    [Migration("20260717165549_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("ms_patients_consul_core.Domain.Aggregates.ConsultationAggregate.Consultation", b =>
                {
                    b.Property<Guid>("ConsultationId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("ConsultationDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsInitialConsultation")
                        .HasColumnType("bit");

                    b.Property<Guid>("NutritionistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ConsultationId");

                    b.ToTable("Consultations", (string)null);
                });

            modelBuilder.Entity("ms_patients_consul_core.Domain.Aggregates.PatientAggregate.Patient", b =>
                {
                    b.Property<Guid>("PatientId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AssignedNutritionistId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("PatientId");

                    b.ToTable("Patients", (string)null);
                });

            modelBuilder.Entity("ms_patients_consul_core.Domain.Aggregates.ConsultationAggregate.Consultation", b =>
                {
                    b.OwnsOne("ms_patients_consul_core.Domain.Aggregates.ConsultationAggregate.BodyMeasurement", "Measurement", b1 =>
                        {
                            b1.Property<Guid>("ConsultationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("FatPercentage")
                                .HasColumnType("float")
                                .HasColumnName("FatPercentage");

                            b1.Property<double>("Height")
                                .HasColumnType("float")
                                .HasColumnName("Height");

                            b1.Property<double>("MusclePercentage")
                                .HasColumnType("float")
                                .HasColumnName("MusclePercentage");

                            b1.Property<double>("Weight")
                                .HasColumnType("float")
                                .HasColumnName("Weight");

                            b1.HasKey("ConsultationId");

                            b1.ToTable("Consultations");

                            b1.WithOwner()
                                .HasForeignKey("ConsultationId");
                        });

                    b.OwnsOne("ms_patients_consul_core.Domain.Aggregates.ConsultationAggregate.NutritionalDiagnosis", "Diagnosis", b1 =>
                        {
                            b1.Property<Guid>("ConsultationId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<double>("Bmi")
                                .HasColumnType("float")
                                .HasColumnName("Bmi");

                            b1.Property<string>("ClinicalAnalysis")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)")
                                .HasColumnName("ClinicalAnalysis");

                            b1.Property<string>("Conclusion")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)")
                                .HasColumnName("Conclusion");

                            b1.Property<string>("Notes")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)")
                                .HasColumnName("Notes");

                            b1.HasKey("ConsultationId");

                            b1.ToTable("Consultations");

                            b1.WithOwner()
                                .HasForeignKey("ConsultationId");
                        });

                    b.Navigation("Diagnosis")
                        .IsRequired();

                    b.Navigation("Measurement")
                        .IsRequired();
                });

            modelBuilder.Entity("ms_patients_consul_core.Domain.Aggregates.PatientAggregate.Patient", b =>
                {
                    b.OwnsMany("ms_patients_consul_core.Domain.Aggregates.PatientAggregate.ClinicalHistory", "ClinicalHistories", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)");

                            b1.Property<Guid>("PatientId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("RegisteredAt")
                                .HasColumnType("datetime2");

                            b1.Property<string>("Type")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.HasKey("Id");

                            b1.HasIndex("PatientId");

                            b1.ToTable("PatientClinicalHistories", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PatientId");
                        });

                    b.OwnsMany("ms_patients_consul_core.Domain.Aggregates.PatientAggregate.EatingHabit", "EatingHabits", b1 =>
                        {
                            b1.Property<Guid>("Id")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(1000)
                                .HasColumnType("nvarchar(1000)");

                            b1.Property<Guid>("PatientId")
                                .HasColumnType("uniqueidentifier");

                            b1.Property<DateTime>("UpdatedAt")
                                .HasColumnType("datetime2");

                            b1.HasKey("Id");

                            b1.HasIndex("PatientId");

                            b1.ToTable("PatientEatingHabits", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PatientId");
                        });

                    b.Navigation("ClinicalHistories");

                    b.Navigation("EatingHabits");
                });
#pragma warning restore 612, 618
        }
    }
}
